language: node_js
node_js:
  - 14
branches:
  only:
    - master
# before_script:
#   - cd functions
#   - npm install
#   - cd ..
script:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: iDuYmIP8Trrhbf07Maj2UzPBb9s/5Je0l6kbBhxkT3EACJKCl9nH047NdgR9RWVPDqsaNModr2m69v+ghQA1BKgtMIzrgo48/YAnZ2aIXKECAtH7+KUoWDoNujS1SVeX3CfC3lIDs/JV6dV4Co1cuUwne32UaRG7Bu982L+zSZmRJ6SHWLRdEkvTwc8HqjGpt1FsHO6VxdwK/M8PR2aXSkTZMxRGzeQ0R5nmsKZYyqKRtMFe2wmxnTmbgXzrD0ytw6pXeSWmTelMqQN1xfcuinDrbJ+buaxO8X4B1PS9Z7NH1SIN+TSbeitUdAf8LUbTWYOW4Se7SmHKvb2xB7SKYcn7qcON2XoNjCLbR2Rc+vd9g8dv9tDzthH1HLkgKBMs2XT5o4nR5QHjuE7Tkpx4y3dy0y/h2aCVRNHZEHJtd7isWDtFY7+frMQIRTHZPw813Ndnp98AQ1TNa+A1EZg4f2X5s2de5KuLVcwSp7y9C6l52Cm3FZPNTCzbfmWmbf79QYfe0CvPomzr0m8ykve45biOuV5wHrK+V63ygn1ZnuxdBb142k7GoZdmmlUWuuqoHZ25Hmss5kjdtOh7ntHO9FtwqPvn5dlMt3zRixAnAYzKGw37JagiF4aVyYZo0bZbD7ubYV54hOg3X42xszTFClwvZ5s2yX5myeQRJdjzIcA=
